# Advanced Portals Config

# To set this file back to its default state just delete it and reload the server or restart it!



# Set to true if you want the normal axes to work normally but the ones gived with /portals selector or wand will still work though
# It can be usefull if people with permission want to use an iron axe on a survival server
UseOnlyServerMadeAxe: false

# Preferably an item and not a block but it shouldnt matter
AxeItemId: IRON_AXE

# Will be implemented so you can give yourself the portal block and build manually with it so its easier to make portals with the portal block.
CanBuildPortalBlock: true

# Defines if portals protect themselves
PortalProtection: true

# How many blocks around the portals will be protected from griefing or destruction
PortalProtectionRadius: 5

# What the default trigger block is for portals if nothing is defined.
DefaultPortalTriggerBlock: PORTAL

# This stops all water flowing inside a portal area(can be disabled if something like world edit is handelling the water flow or you dont want it active)
#    you want to 
StopWaterFlow: true

# This must be a placeable block or it will not work and may even crash
ShowSelectionBlockID: STAINED_GLASS
ShowSelectionBlockData: 14

# WarpEffect
# 0 = disabled(no particles)
# 1 = Eye of ender explode effect(loads of portal particles)
# adding more soon and may create some custom ones
WarpParticles: 1

# WarpSound generally suggested to keep the same as warpeffect but can usually be used for just the sound and no particle effects
# 0 = disabled(no sound)
# 1 = Enderman Warp Sound
# adding more soon
WarpSound: 1

# In case you want to show the bungee attempting warp message
ShowBungeeWarpMessage: false

# This changes how long the show seletion lasts in seconds

ShowSelectionShowDuration: 10

# If a player is riding a entity, warp the entity too?(unless its a bungee portal or any non teleporting portal)
WarpRiddenEntity: true



# Where to display the message 0 = disabled(replaces PortalWarpMessages), 1 = in chat and 2 = action bar(1.8 and above only, anything lower will print the message that would
#  generally on the action bar in the chat without a prefix or extra chat formatting)
WarpMessageDisplay: 2

# Use plugin name in the warp messages
UseWarpPrefix: true

# If this is true a custom prefix can be used, (not fully coded yet!!)

UseCustomPrefix: false

CustomPrefix: '&a[&eAdvancedPortals&a]'

CustomPrefixFail: '&c[&7AdvancedPortals&c]'

PortalCooldown: 5 # How long after trying to enter a portal until the player can try to enter another. 0 or lower to deactivate.

# Not added yet
# PortalCooldownJoin: 5 # How long after the player joins the server until they will be warped. (if a player joins in a portal it will be disabled until they exit it). 0 or lower to deactivate.
